import { Inter } from "next/font/google";
import NavbarUser from "../../components/navbar_user/Navbar_user";
import Footer from "@/components/footer/footer";
export const dynamic = "force-dynamic";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "TPM ecommerce website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <NavbarUser />
      {children}
      {/* // <Footer /> */}
    </div>
  );
}
